{% set name = "argon2-cffi" %}
{% set version = "21.3.0" %}
{% set sha256 = "d384164d944190a7dd7ef22c6aa3ff197da12962bd04b17f64d4e93d934dba5b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - ln -sf $RANLIB $BUILD_PREFIX/bin/ranlib  # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler("c") }}
    - flit-core >=3.4,<4

  host:
    - python
    - pip
    - flit-core >=3.4,<4

  run:
    - python
    - flit-core >=3.4,<4

  run_constrained:
    # avoiding argon2-cffi and argon2_cffi to be installed in parallel
    - argon2_cffi ==999

test:
  imports:
    - argon2

about:
  home: https://argon2-cffi.readthedocs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The secure Argon2 password hashing algorithm.
  description: |
    Argon2 won the Password Hashing Competition and argon2_cffi is the simplest
    way to use it in Python and PyPy
  doc_url: https://argon2-cffi.readthedocs.io/en/stable/
  dev_url: https://github.com/hynek/argon2_cffi/

extra:
  recipe-maintainers:
    - stuertz
